In [1]:
%load_ext autoreload
%autoreload 2

In [4]:
import sys
import os

sys.path.insert(0, os.path.abspath("C://Users//pc//Desktop//Week 1//news_sentiment_analysis//src//"))

In [14]:
from src.data_loader import load_data
from src.sentiment_analysis import normalize_timestamps,adjust_news_to_trading_day,align_on_trading_day
from src.sentiment_analysis import align_news_to_trading_day,add_sentiment_score

print('Functions imported successfully!')

Functions imported successfully!

In [7]:
news_df = load_data('C:/Users/pc/Desktop/Week 1/news_sentiment_analysis/data/raw_analyst_ratings.csv')
news_df.head()

,unnamed: 0,headline,url,publisher,date,stock
0,0,Stocks That Hit 52-Week Highs On Friday,https://www.benzinga.com/news/20/06/16190091/s...,Benzinga Insights,2020-06-05 00:00:00+00:00,A
1,1,Stocks That Hit 52-Week Highs On Wednesday,https://www.benzinga.com/news/20/06/16170189/s...,Benzinga Insights,2020-06-03 00:00:00+00:00,A
2,2,71 Biggest Movers From Friday,https://www.benzinga.com/news/20/05/16103463/7...,Lisa Levin,2020-05-26 00:00:00+00:00,A
3,3,46 Stocks Moving In Friday's Mid-Day Session,https://www.benzinga.com/news/20/05/16095921/4...,Lisa Levin,2020-05-22 00:00:00+00:00,A
4,4,B of A Securities Maintains Neutral on Agilent...,https://www.benzinga.com/news/20/05/16095304/b...,Vick Meyer,2020-05-22 00:00:00+00:00,A

In [9]:
stock_df = load_data('C:/Users/pc/Desktop/Week 1/news_sentiment_analysis/data/AAPL.csv')
stock_df.head()

,date,close,high,low,open,volume
0,2009-01-02 00:00:00+00:00,2.721686,2.730385,2.554037,2.575630,746015200
1,2009-01-05 00:00:00+00:00,2.836553,2.884539,2.780469,2.794266,1181608400
2,2009-01-06 00:00:00+00:00,2.789767,2.914229,2.770872,2.877641,1289310400
3,2009-01-07 00:00:00+00:00,2.729484,2.774170,2.706990,2.753477,753048800
4,2009-01-08 00:00:00+00:00,2.780169,2.793666,2.700393,2.712090,673500800

In [10]:
# normalize timestamps in both datasets
news_df = normalize_timestamps(news_df, "date")
stock_df = normalize_timestamps(stock_df, "date")

In [11]:
# Adjust news timestamps to align with trading days
news_df = adjust_news_to_trading_day(news_df, "date", cutoff_hour=16)

In [12]:
# align datasets
merged_df = align_on_trading_day(news_df, stock_df)

print(merged_df.head())

   unnamed: 0                                           headline  \
0           0            Stocks That Hit 52-Week Highs On Friday
1           1         Stocks That Hit 52-Week Highs On Wednesday
2           2                      71 Biggest Movers From Friday
3           3       46 Stocks Moving In Friday's Mid-Day Session
4           4  B of A Securities Maintains Neutral on Agilent...

                                                 url          publisher  \
0  https://www.benzinga.com/news/20/06/16190091/s...  Benzinga Insights
1  https://www.benzinga.com/news/20/06/16170189/s...  Benzinga Insights
2  https://www.benzinga.com/news/20/05/16103463/7...         Lisa Levin
3  https://www.benzinga.com/news/20/05/16095921/4...         Lisa Levin
4  https://www.benzinga.com/news/20/05/16095304/b...         Vick Meyer

                     date_x stock trading_day                    date_y  \
0 2020-06-05 00:00:00+00:00     A  2020-06-05 2020-06-05 00:00:00+00:00
1 2020-06-03 00:00:00+00:00     A  2020-06-03 2020-06-03 00:00:00+00:00
2 2020-05-26 00:00:00+00:00     A  2020-05-26 2020-05-26 00:00:00+00:00
3 2020-05-22 00:00:00+00:00     A  2020-05-22 2020-05-22 00:00:00+00:00
4 2020-05-22 00:00:00+00:00     A  2020-05-22 2020-05-22 00:00:00+00:00

       close       high        low       open     volume
0  80.390961  80.451587  78.385433  78.414533  137250400
1  78.843788  79.105700  78.159917  78.732237  104491200
2  76.809151  78.630371  76.753371  78.450918  125522000
3  77.332962  77.415413  76.474486  76.576335   81803200
4  77.332962  77.415413  76.474486  76.576335   81803200

In [15]:
 # Align to trading days
aligned_news = align_news_to_trading_day(news_df,time_col="date",market="NYSE")

print(aligned_news.head())

OutOfBoundsDatetime: Out of bounds microsecond timestamp: 9223372108800000000

In [ ]:
# Apply sentiment analysis
news_with_sentiment = add_sentiment_score( news_df, text_column="headline")

print(news_with_sentiment.head())

In [ ]:
# Apply sentiment analysis
sentiment_df = apply_all_sentiments(news_df,text_column="headline")

# Display results
print(sentiment_df.head())